name:                db-migrations
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/db-migrations#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2020 Author name here
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5

executables:
  db-migrations:
    source-dirs:      src
    main:             Main.hs
